### ISSUE TITLE
WSI and bbox json

### ISSUE THREAD

**Issue by naimabe** [CielAl/hovernet_lite#1]
Hi, 

I am trying to run hovernet_lite on a WSI, do you have an example json file for the bbox?

Thank you

**Comment by CielAl** [comment]
> Hi,
> 
> I am trying to run hovernet_lite on a WSI, do you have an example json file for the bbox?
> 
> Thank you

Hi, apologies due to the delayed responses. Here goes a sample JSON file. 
Each JSON file corresponds to the tile location of one WSI, in the format of `List[List[Tuple[left, top, right, bottom]]]`. `Tuple[left, top, right, bottom]` is the 4-tuple coordinate of a single bounding box (bbox).  Tile bbox within the same connected tissue regions are grouped into a list, and multiple connected tissue regions are further grouped into another list. Therefore here goes a nested list of 4-tuple coordinates.

Note that the coordinates are half-open: open at right and bottom. Meaning the actual pixel interval are within [left, right) and [top, bottom), consistent with the convention of other packages like PIL and openslide.

You may feel free to either modify the corresponding code here if you have another format (https://github.com/CielAl/hovernet_lite/blob/main/hovernet_lite/infer/wsi_bbox.py#L71) or you may use HistoQC's TileExtractionModule (https://github.com/choosehappy/HistoQC) to obtain such bounding boxes.

[sample.svs_bbox.zip](https://github.com/CielAl/hovernet_lite/files/12384535/sample.svs_bbox.zip)
